### ISSUE TITLE
Daylight Saving Time

### ISSUE THREAD

**Issue by craigzeller** [sterfa02/GoogleCalendarToSchoology#1]
With the Daylight Saving Time change, the Google calendars that I have where the script is pulling from are all correct. The Schoology events are off by one hour for the entire month of March. Unsyncing and the synching again produces the same errors. Events that were manually added in Schoology sync to my Google calendar with the correct time. Is there any way to pass the correct timezone to Schoology?

Workaround: I checked the Project Properties of my script. It was set to the same time zone that I am in. I change the project properties to a different time zone, unsynced, then set its properties back to my correct time zone, synced, and it worked.

**Comment by samterfa** [comment]
Interesting work around! I will look into this ASAP and get to the bottom of it. Thanks for opening the issue.

**Comment by samterfa** [comment]
Hi Craig- Just a quick update. Schoology does not provide a timezone setting that I have found. Your work-around seems to implicate Google Apps Scripts as being the source of the problem. Unfortunately, I've been using this method of event syncing to sync all day events only so I can't replicate the problem. Adding a new time-based event works as expected. However, I've created an event on a Google calendar I am syncing to a Schoology calendar scheduled around the time of daylight savings in the fall in order to see if I can replicate the issue. Did you see an issue this past fall or were you not using this yet?

Google put out some timezone clarification with regards to their apps script service http://googleappsscript.blogspot.com/2011/03/demystifying-time-zones-in-apps-script_21.html.
